### ISSUE TITLE
Pages & Navigation

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#1]
Create navigation (top nav bar).

There's two views for the navbar, one just includes logo and 'login', the other includes logo, 'My Shop', and 'logout'
- Logo links to homepage
- 'Login' goes to authentication
- 'My shop' goes to vendor admin page
- 'Logout' just changes navbar so it only shows logo and 'login'

For each navbar link, create an empty page.

**Comment by JonCote** [comment]
Pushed new Navbar, auth, and routing based on @maddiesolis previous work. Improvements allow for easier expansion/alterations to navigation, authentication, and routing. Approximately 3.5hrs work done
