### ISSUE TITLE
Artist preview component

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#3]
Just this component, goes on the homepage.
- Artist/shop name
- Logo/thumbnail
- Side scroll catalogue of ~5 item images (maybe hover state on each image shows the item name & price)
- Description

![Image](https://github.com/maddiesolis/seng480/assets/105009134/dbe49f7d-f10d-47f2-9970-c2c5f5d1b592)

**Comment by j7uu** [comment]
Merged
