### ISSUE TITLE
Set up API's for CRUD

### ISSUE THREAD

**Issue by julhoang** [MarketMate-Seng480/MarketMate#46]
**Context:** For data security reason, we don't want to communicate with the database directly from the client-side, especially as the data might contain userID's from authentication. 

**Task:** Setting up the APIs endpoints and corresponding Prisma requests to communicate with database. 
Please implement these and feel free to add anything else that makes sense for our app:
- Create single record
- Read: get record by ID, get all records, get a filtered list of records
- Update a single record
- Delete a single record, delete multiple record
Create separate endpoints for each of these, as applicable. 

**Resources:**
https://nextjs.org/docs/app/building-your-application/routing/route-handlers
https://www.prisma.io/docs/orm/prisma-client/queries/crud

**Comment by JonCote** [comment]
after adding the events endpoints time spend is approximately 8hrs. Spent most of my time researching api implementation best practices, nextjs+prisma api implementations, and designing our api endpoints to best fit our current needs while being easy to expand on.
