### ISSUE TITLE
Update Cart Prisma Schema and Cart API

### ISSUE THREAD

**Issue by maddiesolis** [MarketMate-Seng480/MarketMate#89]
**Task**: Update the backend piece for Cart functionality.
- Add `cartId` column to `User` table
- Find and implement best way to store multiple products and quantity per product in `Cart` table (probably a JSON object)
- Add product quantity tracking to `Cart`

Implement cart API endpoints

Connected to [this issue](https://github.com/orgs/MarketMate-Seng480/projects/2/views/1?pane=issue&itemId=56101129) (frontend piece of Cart)

**Comment by JonCote** [comment]
approximately 4-5hrs total spent researching database schemas, updating database, and implementing the cart API
